### ISSUE TITLE
GetField(), TryGetMember(), and HasField() methods on DynamicRecord throw NullPointerException when a record contains a field which is no longer part of a form

### ISSUE THREAD

**Issue by ThoughtProcess** [umbraco/Umbraco.Forms.Issues#114]
If you modify a form to remove one or more fields, you will encounter a NullPointerException any time you try to call certain methods on a DynamicRecord object that represents an old record which contains data from those deleted fields.

Reproduction
------------

1. Create a form with one or more fields.  For example, "Name" and "Address"
1. Submit the form multiple times, so you have a series of records that contain values for those two fields.
1. Delete the "Address" field.  
1. Save the form.
1. Elsewhere in your code, iterate through the records that belong to the form that you just changed.

```
using (var formStorage = new FormStorage())
{
   using (var recordStorage = new RecordStorage())
   {
       var form = formStorage.GetForm(Guid.Parse("ede58fd2-9eff-4f88-a5d6-053042983681"));
       var records = recordStorage.GetAllRecords(form).Where(x => x.UmbracoPageId == Model.Content.Id && x.State == FormState.Approved).ToList();
       foreach (var record in records)
       {
           // This will throw a NullPointerException
           // Note that the argument for .HasField() doesn't have to be "Address" -- it will now throw NPE's for _any_ input.
           if (Model.HasField("some_field_literal"))
           {
               // ...
           }
       }
   }
}
```

### Expected result

I should be able to call the "usual" methods on DynamicRecord.

### Actual result

I get a NullPointerException when I call `GetField()`, `TryGetMember()`, and `HasField()`.

The Bug
------------

I poked around in DotPeek, and I think the issue stems from the following implementation:

```
// Raw DotPeek output
public bool HasField(string caption)
    {
      return this._record.RecordFields.Where<KeyValuePair<Guid, RecordField>>((Func<KeyValuePair<Guid, RecordField>, bool>) (f => f.Value.Field.Caption == caption)) != null;
    }
```

I suspect this code originally looked something like this:
```
public bool HasField(string caption)
    {
        return _record.RecordFields.Any(f => f.Value.Field.Caption == caption);
    }
```

When a field is deleted from a form, any record that contains data for that zombie field will have a `null` value for the corresponding `RecordField.Value.Field`.  This means that dereferencing `RecordField.Value.Field.Caption` would trigger a `NullPointerException`.

How about something like this as a workaround?

```
public bool HasField(string caption)
    {
        return _record.RecordFields
            .Where(f => f.Value.Field != null)
            .Any(f => f.Value.Field.Caption == caption);
    }
```

I think a similar convention could be applied to other places in the class where the `Value.Field.Caption` is referenced in a LINQ expression.

Possibly related to #96 and #101 ?

**Comment by bergmania** [comment]
I'm pretty sure this is fixed by https://github.com/umbraco/Forms/commit/54b3a3a55dd97e2119054b8b9ac6656b08439540?w=1.

The issue was caused because the field returned for the data was `null`.

The fix is part of the next release.

**Comment by ronaldbarendse** [comment]
Looks like this issue is related to #133 and still not (completely) fixed...
