### ISSUE TITLE
RTE is missing formatting options when changing from any field type to RTE

### ISSUE THREAD

**Issue by ppsyrra** [umbraco/Umbraco.Forms.Issues#1476]
### Which Umbraco Forms version are you using? (Please write the *exact* version, example: 13.4.0)

16.1.0

### Which Umbraco version are you using? (Please write the *exact* version, example: 13.5.2)

16.3.0

### Issue summary

In the form, when changing the field type from any to an RTE, the RTE is missing the formatting options. 

https://github.com/user-attachments/assets/ebd1c8fa-d259-4442-b1b3-b9d74dd26ea0

### Steps to reproduce

- Create new form
- Select a new question
- Select a field type other than RTE, for example Date
- Add all the necessary infos and submit
- On the form, click to edit this question
- Change the field type from Date to RTE

Outcome: the RTE is missing the formatting options

### Expected result / actual result

Expected: the RTE should keep the formatting options when changing from one field type to another 

---
_This item has been added to our backlog AB#61210_

**Comment by mattbrailsford** [comment]
I have successfully reproduced this so will add it to our backlog to look at in an upcoming sprint.

It doesn't look critical though as once the RTE is selected, you can submit the modal then re-open it and it does then have the formatting buttons so it's not completely blocking functionality.

**Comment by rickbutterfield** [comment]
Hi @ppsyrra! A fix has been released in 16.5.0-rc and 17.2.0-rc, please test it out and report back.

**Comment by ppsyrra** [comment]
Dear @rickbutterfield , tested in v17.2 and the issue is still present

**Comment by rickbutterfield** [comment]
Hi @ppsyrra! Please give the final release of Forms 17.2.0 a try and report back

**Comment by stef4905** [comment]
I see the same problem and just tested with the 17.2.1 version. I can confirm that the issue still exists.

<img width="761" height="785" alt="Image" src="https://github.com/user-attachments/assets/889b56db-0fb2-4529-9f52-3a9cfcb4750c" />

**Comment by ppsyrra** [comment]
Hello @rickbutterfield I just tested with Umbraco forms v17.2.1 and I **cannot** reproduce the issue.
