### ISSUE TITLE
SQL Database Prevalue Source requires both the 'Connection String' and 'Connection String from web.config' values to be entered/selected

### ISSUE THREAD

**Issue by ribsdigital** [umbraco/Umbraco.Forms.Issues#223]
When creating a new 'Prevalue source' with a type of 'SQL Database' the editor requires you to enter a 'Connection String' value and select a value 'Connection String from the web.config'

### Steps to reproduce

1. Create a new 'Prevalue source'
2. Give it a name
3. Select a type of 'SQL Database'
4. Click save

### Expected result
You should be able to either enter a connection string or select a connection string from the web.config.

### Actual result
The editor errors stating 'Prevaluesource failed to save: 'Connection' setting has not been set' unless both the 'Connection String' has a value entered and the 'Connection String from web.config' has a selected value.

---
_This item has been added to our backlog [AB#2611](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2611)_

**Comment by nul800sebastiaan** [comment]
That's weird, that's a bug that should be fixed, thanks!

**Comment by redshift520** [comment]
I see this issue listed as fixed in the Umbraco Forms release notes for forms version 7.2.0, however, I've updated and there's no change.  I also clean installed Umbraco 7.15.4 and Umbraco Forms 7.4.1 and the issue still exists.

**Comment by ribsdigital** [comment]
i can't reopen this issue so i've reported it as the bug still exists in the latest version on 8.6.1

[https://github.com/umbraco/Umbraco.Forms.Issues/issues/495](https://github.com/umbraco/Umbraco.Forms.Issues/issues/495)
