### ISSUE TITLE
Apostrophe in email address gets escaped - email won't send

### ISSUE THREAD

**Issue by Coderophenia** [umbraco/Umbraco.Forms.Issues#345]
If an email address submitted on a form has an apostrophe in it, it is not possible to use that field as the receiver email address. The apostrophe gets escaped to \\' and the email fails.

Note: hard coding email address into workflow works. It only fails when populated from the form using magic strings i.e. {emailAddress}

Reproduction
------------

### Specifics

Bug tested and occurring in version 7.1.1 and 7.0.6

### Steps to reproduce

Create a form with a short answer field validated as email address named email Address. 
Use this field as the receiver email in a workflow using magic sting: {emailAddress}. 
Submit the form using an email address with an apostrophe e.g. testo'tester@test.com.

### Expected result

Expected email to send

### Actual result

Form will submit but email won't be sent. Logs show error below.

    ERROR Umbraco.Forms.Core.Providers.WorkflowTypes.SendRazorEmail - 
    There was a problem sending a Razor email to 'test\'otester@test.com' from Workflow for Form 'Test Form' with id 'xxxx' for Record with unique id 'xxxx'   
    System.FormatException: An invalid character was found in the mail header: '\'.
    at System.Net.Mail.MailAddressParser.ParseLocalPart(String data, Int32& index, Boolean expectAngleBracket, Boolean expectMultipleAddresses)
    at System.Net.Mail.MailAddressParser.ParseAddress(String data, Boolean expectMultipleAddresses, Int32& index)
    at System.Net.Mail.MailAddressParser.ParseMultipleAddresses(String data)
    at System.Net.Mail.MailAddressCollection.ParseValue(String addresses)
    at System.Net.Mail.MailAddressCollection.Add(String addresses)
    at Umbraco.Forms.Core.Providers.WorkflowTypes.SendRazorEmail.Execute(Record record, RecordEventArgs e)`

---
_This item has been added to our backlog [AB#6746](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6746)_

**Comment by nul800sebastiaan** [comment]
Thanks @Coderophenia - I am just wondering: is it even supported to have apostrophes in email addresses? Seems.. complicated, if it is.

**Comment by c9mbundy** [comment]
@nul800sebastiaan  I'm afraid it is - there is a bunch of RFC specs for this but Wiki has a decent summary article https://en.wikipedia.org/wiki/Email_address#Local-part. 

However, I believe that it is now even valid to use unicode characters in both the local-part (alias) and the domain, as a result of the IDNA work... that should make for a fun regex.

**Comment by CTRPaul** [comment]
We've had this issue too. It'd be helpful if it was resolved, as we've got lots of Umb forms licenses and have had this raised as an issue numerous times, not sure what we can do about it though as the problem is within Forms.

**Comment by Coderophenia** [comment]
Any updates on this? It's becoming an increasing issue for us. Users think they've submitted a form (and they have) but no-one knows. I suspect this to be a fairly large issue, but as it fails silently most site owners will be unaware.

**Comment by Pauldubbya** [comment]
Still having to live with this issue that impacts all versions of forms it seems. With more and more people having these sort of characters in their email addresses it's getting more pressing; I'm very surprised it's not cropped up earlier TBH.

**Comment by Pauldubbya** [comment]
What do we need in terms of "needs-more-info" on this one @nul800sebastiaan ?

**Comment by nul800sebastiaan** [comment]
@Pauldubbya I just needed to test this out.. 

I found the problem, I think it was only the XSLT email workflow that was affected, can anyone confirm? In any case, I've fixed it and tested all 3 email types of workflows and they work with an apostrophe now as of the upcoming v7.5.0 version.

**Comment by Pauldubbya** [comment]
@nul800sebastiaan it wasn't the XSLT workflow for me that causing an issue, but glad to hear it's solved. #legend 👍 

Do you have a rough idea of when we can expect Forms 7.5 ?

**Comment by Pauldubbya** [comment]
Just tired this with UmbForms 7.5.4 and it's still not working for me. 

ERROR Umbraco.Forms.Core.Services.WorkflowService - Form workflow 'Send email' failed on 'Submitted' of Record with Unique ID 'XXXX-XXXX' from the Form named 'Test apostrophe' with Unique ID 'XXXX-XXXX'
System.FormatException: An invalid character was found in the mail header: '\'.

:-(

**Comment by Coderophenia** [comment]
We've just upgraded to 7.5.4 and are still getting an issue with emails having apostrophes in them.
### **Workflow**
![workflow](https://user-images.githubusercontent.com/64526727/126772262-bdb87fe0-6b6b-43f5-b393-6f773d6bfe07.jpg)
### **Log error**
![error](https://user-images.githubusercontent.com/64526727/126772261-0330b1c2-5adb-4e12-8570-feeacda9f812.jpg)

**Comment by Pauldubbya** [comment]
@umbrabot open issue
