### ISSUE TITLE
Unable to load form: Could not find file 'xxx.json' in the folder workflows

### ISSUE THREAD

**Issue by lukehook** [umbraco/Umbraco.Forms.Issues#407]
A brief description of the issue goes here.

Existing Umbraco Cloud project with Forms. Upgrade to 8.5.3.

'Unable to load form: Could not find file 'xxx.json' in the folder workflows' error after removing prevalue source from a field.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Existing Umbraco Cloud project with Forms. Upgrade to 8.5.3.

When removing a prevalue source from a form field I am unable to save the form (the logs seem to imply the json is missing for the prevalue).

Then clicking to a different form and then back to the previous form you are met with an exception as the form json is missing. The form and all of it's fields and configurations seem to have been lost. This is affecting baseline child sites we have in production.

### Specifics

- Umbraco Cloud - CMS version 8.7
- Umbraco Forms - 8.5.3
- Umbraco Deploy - 3.5.0

### Steps to reproduce

- Create a form on a pre-forms 8.5.0+ site with a prevalue source
- Upgrade forms to 8.5.0+
- Remove prevalue source from field
- Try to save form (should fail)
- Leave Forms in the CMS and return to configured form
- Should be presented with the above exception 'Unable to load form: Could not find file 'xxx.json' in the folder workflows'

(where 'xxx' is the guid of the form in questions)

### Expected result

Form should save and configuration be accessible after configuration change

### Actual result

Presented with the above exception 'Unable to load form: Could not find file 'xxx.json' in the folder workflows'

![FormsError](https://user-images.githubusercontent.com/7995797/93346821-49e1b680-f82c-11ea-904c-775fa152ad69.gif)

---
_This item has been added to our backlog [AB#8851](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8851)_

**Comment by nul800sebastiaan** [comment]
Guessing Forms version 8.5.3? 😉 
hat is the `StoreUmbracoFormsInDb` setting for you in `UmbracoForms.config`? Problem might be related to https://github.com/umbraco/Umbraco.Forms.Issues/issues/401

**Comment by warrenbuckley** [comment]
I am currently unable to reproduce this, see the attached video

[Video trying to reproduce bug 407](https://umbracocloud-my.sharepoint.com/:v:/g/personal/warren_umbraco_dk/EVnKnFXUb95JpNQglluS16IBzwk4i5Gig_fer5ylyLALOw?e=B4qIcw)
Password: `407`

My next steps are to reach out to the cloud support team, to see if they have encountered this or can give me some repro notes

**Comment by dangander** [comment]
I have this problem reliably on my cloud project - 8.8.0 with Forms 8.5.3
Bug seems to manifest fairly randomly without changes being made, but it does happen every time.

1. Start with a blank 8.8.0 cloud project with forms 8.5.3
2. Create a form - form I used had short text and drop down question answer types
3. (this seemed to be the big one) Add a "send for to URL" workflow type
4. Add the form to a page and submit it once
5. Try to open the form in backoffice and you'll get the error

I repro'd the bug 5 times consecutively on cloud with this method, so seems fairly reliable. I'd record it for you, but my site is still offline with today's outage!

**Comment by dangander** [comment]
@warrenbuckley I've recorded reliable repro for you - still happening on Forms 8.5.4 (Umbraco 8.8.1)
It's actually simpler than my earlier description; no need to submit the form. Seems to be related to configuring certain workflow types.
[Repro video](https://besagroup-my.sharepoint.com/:v:/g/personal/dan_gander_thebesa_com/EYSsPyInNndFsX1kPfSM2cUBV7NMKIRareX59QkulE5ufA?e=ACfYtml)
Password is 407

**Comment by warrenbuckley** [comment]
This got merged into v8/dev @nul800sebastiaan we do not have a 8.6.0 release label/tag or is this due for 8.5.x ?

**Comment by brightspectrum-da-bomb** [comment]
Is this issue closed? If so what is the solution? I am having the same issue on forms 8.5.5.  I deleted a workflow and then the form would not load in the backend or the UI stating that a .json workflow file was missing. I added a blank version of that file back and it works but then it is adding multiple of the workflow steps which cannot be deleted.

**Comment by nul800sebastiaan** [comment]
This issue is fixed for the upcoming 8.6.0 version (I don't know yet what the expected release date is unfortunately).

**Comment by sanzandsanz** [comment]
There are still some jquery code in the umbracoform.js file. 

` else if ($ && $.validator !== undefined) {
            //Jquery validation setup

            $.validator.setDefaults({
                ignore: ":hidden"
            });

            $.validator.unobtrusive.adapters.addBool("requiredcb", "required");


            $.validator.addMethod("umbracoforms_regex", function (value, element) {

                var regex = $(element).attr("data-regex");
                var val = $(element).val();
                if (val.length === 0) {
                    return true;
                }
                return val.match(regex);
            });

            $.validator.unobtrusive.adapters.addBool("regex", "umbracoforms_regex");

            var submitInputs = document.querySelectorAll(".umbraco-forms-form input[type=submit]:not(.cancel)");
            for (var i = 0; i < submitInputs.length; i++) {
                var input = submitInputs[i];
                input.addEventListener("click", function (evt) {
                    evt.preventDefault();
                    var frm = $(this).closest("form");
                    frm.validate();
                    if (frm.valid()) {
                        frm.submit();
                        this.setAttribute("disabled", "disabled");
    
                    }
                }.bind(input));
            }
        }`

**Comment by dangander** [comment]
This is still an issue on Umbraco 8.9.0 / Forms 8.5.5:
Add a workflowtype to a form "Send Form to URL".

1. - Configure some mappings (static or not).
2. - Save the form.
3. - Navigate away from, then back to the form.
4. - Edit the new workflowtype (the mappings will now be blank)
5. - Renter the mappings
6. - Save
7. - The form .json file is now missing
