### ISSUE TITLE
The provided anti-forgery token was meant for a different claims-based user than the current user.

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#485]
Since we've updated to Umbraco Forms 8.6 using Umbraco 8.10.2 we've get al lot of these errors:
```

2021-02-09 20:23:48.468 +01:00 [Error] An unhandled exception occurred System.Web.Mvc.HttpAntiForgeryException (0x80004005): The provided anti-forgery token was meant for a different claims-based user than the current user.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at Umbraco.Forms.Core.Attributes.ValidateFormsAntiForgeryTokenAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)


```

Reproduction
------------
We don't know when this error occures exactly. It's not in alle cases when users submit a form.
In the Umbraco Forms 8.4.1 version (using Umbraco 8.6.4) we've used, this error didn't occure.
We use the macro to insert the form in a grid.

Is it maybe related to this issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/175 ?

**Comment by mcl-sz** [comment]
Can it be related to this topic: https://our.umbraco.com/forum/umbraco-forms/97792-umbraco-forms-error-anti-forgery-cookie-token-and-form-field-token-do-not-match ?

**Comment by nul800sebastiaan** [comment]
Hi @inetzo and sorry for the late reply, I didn't catch this issue in time! I need some more info on how to reproduce the error, you say this error happens a lot, when does it happen exactly and is there a way you can make it happen so we can try it out and see if that can be fixed. So far I've not seen this error being reported by other people so it could possibly be something specific to your setup, not sure. #175 was a very specific error that has long since been fixed, but points to some caching, maybe if you added your own caching to macro's it could be causing this problem.

Anyway, let us know some more steps to reproduce and we can have a look! 👍

**Comment by inetzo** [comment]
Thanks fot your reply @nul800sebastiaan , we use Forms in an intranet enviroment. We're using Indentity for member authentication. When we've updated Forms we've also updated Umbraco and UmbracoIdentity. This makes it difficult to determine which part is causing the problem. We do not use our own caching method, but given the message there is an anti-forgery token, but it does not appear to belong to this user/member. Because it is an intranet, members must log in anyway to use a form. In your opinion, is it an objection if we therefore disable anti-forgery?

**Comment by nul800sebastiaan** [comment]
I don't think you can actually disable anti forgery since it's build into Forms (not an option).

Can you tell me a bit more: 
- when does it happen exactly and is there a way you can make it happen so we can try it out and see if that can be fixed
- does your intranet use load balanced servers at all, or multiple frontends?
- do users see this error or is it only present in your logs?

I doubt that it has to do with UmbracoIdentity, that should "just" work.

**Comment by inetzo** [comment]
```
    <!-- AntiForgeryToken - See documentation here: https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Developer/Configuration/ -->
    <setting key="EnableAntiForgeryToken" value="True" />
```
This setting in UmbracoForms.config suggests that it is possible to turn it off. Or is this legacy?

The thing is that we have 6000+ users and we don't know by who or on which page/form it is happeing. However, we don't get any complaints about members receiving an error message. 
We don't use loadbalancer or multiple frontends. But we do use a Citrix Netscaler to make it accessable to the outside, users with the domain accessing the server directly.
But during testing forms got submitted correctly in all situations (with or without Netscaler) and browsers.

**Comment by inetzo** [comment]
I a fresh installation of UmbracoForms i can't find @Html.AntiForgeryToken() in Form.cshtml as documentation says. It does exist in Render.cshtml. What is the difference between Form.cshtml and Render.cshtml, when is which used?

**Comment by inetzo** [comment]
I have done some further research and it seems that under some circumstances the problem occurs when a user and a member are logged in at the same time/same browser. When a member is logged in (via ADFS), we check if there is also a user with the same username. If this is the case, we also log the user in so that they can go to the backoffice without logging in again. However, I cannot reproduce it yet but it looks it has something to do with it..

**Comment by inetzo** [comment]
@nul800sebastiaan is there a known issue/ side effect that Antif-orgery can cause an error message when a member and a user are logged in at the same time within the same browser?

**Comment by nul800sebastiaan** [comment]
Sorry for the late reply. I didn't know that setting existed, cool!

So in Forms were using "regular" ASP.NET request verification, meaning when there's a form on the page there's a hidden input with the name `__RequestVerificationToken`. When you submit the form we do `System.Web.Helpers.AntiForgery.Validate();` (unless you set `EnableAntiForgeryToken` to `False`). 

I am guessing that your solution ALSO puts a `__RequestVerificationToken` either on each page or somewhere in the request collection (cookie?). I have tested this with a regular Umbraco install where I'm logged in as a member, and a user and have a form on the page and that works just fine. So the question is, do you see multiple `__RequestVerificationToken` fields maybe? At least you should be able to see them in the `POST` request.

**Comment by inetzo** [comment]
We've disabled AntiForgeryToken by changing EnableAntiForgeryToken to false. The form does get submitted now but the wierd thing is that the member details are missing. We're using an custom AuthorizeAttribute and this does return true.

```

    public class CustomAuthorizeAttribute : AuthorizeAttribute
    {
        protected override bool AuthorizeCore(HttpContextBase httpContext)
        {
            var helper = Current.Factory.GetInstance<MembershipHelper>();
            return helper.IsLoggedIn() && string.IsNullOrEmpty(helper.CurrentUserName) == false;
        }
       ......
  }
```
In the mailtemplate  we're using var member = Members.GetCurrentMember(); to get the member that is submitting the form. When this problem occures, the Members.GetCurrentMember() returns null, but the request does get authorized via the attribute above, so the CurrentUserName can't be null or empty.

**Comment by inetzo** [comment]
We have further investigated this issue. In about 90% of the cases when this problem occurs, an iPhone with Safari is used. The other 20 percent are various other browsers such as Internet Explorer, Firefox and Android devices. But mostly iPhones give issues while most users are using Firefox or Internet Explorer.

What can be the reason that the membership helper says that member IsLoggedin and the CurrentUsername isn't null or Empty but that the member = Members.GetCurrentMember() returns null?

**Comment by inetzo** [comment]
I've compared the Context.Request.Params from an succesfull form submit and a form submit where Members.GetCurrentMember() returns null.

In the submit without member, the items "AUTH_TYPE", "AUTH_USER" and "REMOTE_USER" are empty. In a succesfull submit the "AUTH_TYPE" = "ApplicationCookie" and "AUTH_USER" and "REMOTE_USER" contain the member username.

Both the requests, with or without member, contain `Cookie: UMB_UCONTEXT_MEMBERS=.....`
All pages are protected with CustomAuthorizeAttribute  above. While debugging it looks like the CustomAuthorizeAttribute is always validated before the Form workflows are executed. A member can't access any pages (with or without forms) if they are not authorized.

**Comment by c9mbundy** [comment]
Are you using any html caching? Partial-Caching in particular, is problematic with the way Umbraco deploys the use of Anti-Forgery.

**Comment by inetzo** [comment]
No we don't use caching and at the moment we've disabled Anti-Forgery for Forms. 

Whats wierd is that we've added an workflow that mails us when Members.GetCurrentMember() == null and in the details you can see that User.Identity.IsAuthenticated = False while the MembershipHelper.IsLoggedin also uses this to check if a member is authenticated. 

```
Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1
HasHttpContext: yes
UmbracoContext.HttpContext.User.Identity: 
Members.CurrentUserName: 
User.Identity.Name: 
User.Identity.IsAuthenticated: False
UmbracoContext.HttpContext.User.Identity.IsAuthenticated: False
```

**Comment by inetzo** [comment]
We've found what might be causing this problem: When a user (mainly) on an iPhone fills out a form and lands on the thank you page and leaves this tab open, then reopens Safari after a while, the form is automatically resubmitted. The session of the member has already expired (so no longer logged in) but because the POST runs via "umbraco/RenderMvc?" instead of the original page url , the authenticationproces of the member is not performed again, so it cannot be determined which member has submitted the form.

Is it possible somehow to build in that once a form has been completed it cannot send the POST request again when the thank you page is shown?

**Comment by AndyButland** [comment]
I think the way you can do this is rather than presenting the message, use the other option to redirect to a "thank you" page.  That's arguably a better practice anyway, as it following the ["post / redirect / get"](https://en.wikipedia.org/wiki/Post/Redirect/Get) model and you avoid issues with form reposting when someone refreshes the browser.  The browser will usually warn you in this situation, but even so it's a little confusing for the user.

**Comment by inetzo** [comment]
My apologies, I think I didn't explained it correctly (I'm not a native English speaker). Most of our CMS-users use the "Thank you"-message, not the thank you page. The problem occurs with forms with a "Thank you"-message. Is it possible to include in Umbraco Forms that "Thank you"-message is also shown by means of "post / redirect / get" instead of a direct result of the POST?

**Comment by AndyButland** [comment]
No need to apologise, I understood but perhaps my response wasn't very clear.  Really I was just advising that if your CMS-users used the "thank you page" that would likely give a better experience for the users and avoid this issue - but sounds like you are already aware of that.  I'll have a think about whether we could change the behaviour of the message too.

**Comment by warrenbuckley** [comment]
Fixed by this PR
https://github.com/umbraco/Forms/pull/556

Due for release in 8.8.0

**Comment by kbha-syddjurs** [comment]
Hi @warrenbuckley 

I'm using Umbraco Forms 8.13.4 and the error still occurs sometimes. I can't see the PR so i don't know how you fixed the bug. Can you explain how to fix the bug and why it isn't fixed in version 8.13.4? :)

**Comment by AndyButland** [comment]
Hi @kbha-syddjurs - the update here was to ensure that whatever method is used for post submission (either presenting a message or redirecting to another page) a fully "post / redirect / get" action is used.  This would avoid the issue described in the comments above where a form is resubmitted when the post-submission message is displayed.

**Comment by Matthew-Wise** [comment]
Hi all,

Form is doing a full page reload using a POST. This is not an issue locally or on live but is an issue on our Cloud Dev site. @AndyButland  happy to give you access if you need :) 

Thanks
Matt
