### ISSUE TITLE
Unable to load form: User does not have access to the form with id

### ISSUE THREAD

**Issue by DrKirk84** [umbraco/Umbraco.Forms.Issues#764]
After creating a new form with an non admin user, the user get's the success message "Form saved" and after that, the error message "Unable to load form: User does not have access to the form with the id: form-guid". The form is not loading. If the user refresh the page, the form loads without an error. The exception is thrown by ValidateAccessToForm in the Umbraco.Forms.Web.Editors.FormController. If I move the user to the Administrations Group, no exception is thrown after saving the form.

**Umbraco Version:** 9.4.1
**Umbraco Forms Version:** 9.3.0

![grafik](https://user-images.githubusercontent.com/84323988/163996195-0944eab4-2bfd-4cc1-8ef7-419c5ae980db.png)

The User should have full access:

![grafik](https://user-images.githubusercontent.com/84323988/163996654-034eeb85-c72a-47a0-9799-00d97fda7a4f.png)

the group permissions for the user:

![grafik](https://user-images.githubusercontent.com/84323988/163999646-cd66ea8b-9270-4db9-b4a6-88a4a8db031d.png)
![grafik](https://user-images.githubusercontent.com/84323988/163999706-fad81196-c107-46d2-8834-e44bab6000f8.png)

### Steps to reproduce

Install Umbraco 9.4.1 and Umbraco Forms 9.3.0. Create a new User without admin role and try to create a new empty Form. After saving the form you should get the success and the error message.

### Expected result

The form should be loaded without any errors.

**Comment by AndyButland** [comment]
Thanks for reporting.  I actually ran into this one myself when testing the release candidate for 9.4.0, and resolved it, so you should find this fixed in that version.  The full release for 9.4.0 is expected on Tuesday 26th April.

**Comment by DrKirk84** [comment]
@AndyButland I updated to Umbraco Forms Version 9.4.0 but I still get the error.
![image](https://user-images.githubusercontent.com/84323988/165321172-79da9b61-9bc7-42d7-8ea6-d4444ff0322a.png)
![image](https://user-images.githubusercontent.com/84323988/165321442-d5b617f0-03eb-4510-a5bd-1d46ed9751c8.png)

**Comment by AndyButland** [comment]
Yes, I see.  Unfortunately this wasn't the issue I found in testing the RC, there was clearly something else too.  Looks like the issue manifests itself when you aren't using the option to manage security with groups.  It does resolve itself with a refresh, but as you've found, immediately after creating a form, the non-admin user doesn't have access to it.

I've got a fix prepared for this which we'll release in the next patch for Forms, likely in a couple of weeks.  If it's blocking you or you otherwise can't wait for that, please let me know and I can see about getting a pre-release available for you.

**Comment by DrKirk84** [comment]
Thanks Andy for the quick response. It is fine if the fix is in the next release 👍

**Comment by bjornnorlen** [comment]
@AndyButland Do you have any date on when the patch will be released? :) On the Umbraco forms page it looks like 9.4.1 already has been released but I was not able to upgrade to that version: https://our.umbraco.com/packages/developer-tools/umbraco-forms/

**Comment by AndyButland** [comment]
Sorry, that's my mistake in copy/pasting... it's due out next Tuesday.  I've updated the page now to have the correct date.

**Comment by bjornnorlen** [comment]
@AndyButland I'm not sure if this is a feature request but I still have issues with users who are not admin and therefore not able to see their newly created forms. There are three properties in the security section in appsettings.json which I think are relevant and these are my configurations for them:

- "DefaultAccessToNewForms": "Grant",
- "ManageSecurityWithUserGroups": true,
- "GrantAccessToNewFormsForUserGroups": "admin,editor,formsadmin"


I have a user group, let's call it "Company 1". If I add that user groups alias to the GrantAccessToNewFormsForUserGroups value then there isn't an issue for editors to access their newly created forms but then that means that I have add every user group alias to the fields value so the editors can edit their created forms. Is that how it is supposed to work? What I would like to accomplish is to create new groups in Umbraco, select a start folder at the group level in the forms security section and then by default let every user access their newly created form and other forms in the folder they have access to. I tried settings the value of GrantAccessToNewFormsForUserGroups to an empty string and then to remove the property entirely but none of them worked.

**Comment by AndyButland** [comment]
Hi @bjornnorlen - it sound like we need an extension here, adding some more options to the `GrantAccessToNewFormsForUserGroups` setting.  As you say, this setting can be used to achieve what you are looking for but only if you configure it with all the groups.  And I appreciate if you are regularly adding them, it's not great to have to change this configuration as well and restart your site.

Perhaps we could add two further options:

- A setting of "all" - which would grant access to the new form for all user groups.  So you wouldn't have to list them all individually.
- A setting of "form-creator" - which would grant access to the new form to all user groups that the creator is part of.

Does or other other (or both) sound like it would do the job for you?

**Comment by bjornnorlen** [comment]
@AndyButland Yeah definitely, I think they would be great additions and get the job done :)

**Comment by AndyButland** [comment]
These additional settings will be available from the next release.
