### ISSUE TITLE
Dates show as null in the form entry full view 10.1.0

### ISSUE THREAD

**Issue by jamesrichardbrett** [umbraco/Umbraco.Forms.Issues#848]
Values saved using the Date field are being shown as null when clicking through to see all fields (fine in the listing summary). We are using a custom theme so also switched to use the default theme and got the same results.

Reproduction
------------

Create a form using a date picker field
Reference the field
Submit the form
Looking in the Back office form entries

### Specifics

Umbraco v 10.1.0
Umbraco Forms v 10.1.0 and v 10.0.5

So fine here:

![image](https://user-images.githubusercontent.com/108122423/185877065-45b79c37-3def-4362-be75-096e2f8812fc.png)

Not fine here:

![image](https://user-images.githubusercontent.com/108122423/185877161-cff01d3f-48a6-4928-ac1d-54d1b9b26405.png)

### Expected result

I expected to see the actual date

### Actual result

null

**Comment by AndyButland** [comment]
I can't immediately replicate this, so could I ask for a bit more information please?

If you find the unique Id of one of these test records (visible on the screen where you see the full details of the entry), could you send me the results of this query please?

```
SELECT RecordData,Culture FROM UFRecords WHERE UniqueId = '<unique id of record>'
```

Also please can you let me know the language that is being used by the back-office user (found under "Language" in the user details screen in the "Users" section)?

Finally, if you have any value set for this configuration option: `CultureToUseWhenParsingDatesForBackOffice` - please could you let me know what it is?

Thanks.

**Comment by jamesrichardbrett** [comment]
Hi Andy

Thanks for getting in touch. Here are the required screenshot:

***@***.***


***@***.***


***@***.***

***@***.***

Cheers
James

**Comment by jamesrichardbrett** [comment]
Sorry forgot to mention the value CultureToUseWhenParsingDatesForBackOffice is not set anywhere.

j

**Comment by AndyButland** [comment]
I'm afraid nothing has come through on the GitHub issue.

**Comment by jamesrichardbrett** [comment]
![image](https://user-images.githubusercontent.com/108122423/185936491-ca8bb494-40cf-4069-9407-0a5a57e5e274.png)

![image](https://user-images.githubusercontent.com/108122423/185936766-41f4e8e8-3ff7-4809-97b9-7a4be4b44e58.png)

![image](https://user-images.githubusercontent.com/108122423/185936989-7cda325d-a858-4b1c-a96f-9292809349e7.png)

**Comment by AndyButland** [comment]
Thanks, however that's missing the part I was hoping to see.  Would you mind running this query and sharing the results please?

```
SELECT RecordData,Culture FROM UFRecords WHERE UniqueId = '<unique id of record>'
```

**Comment by jamesrichardbrett** [comment]
Hi Andy 

It's actually the last screenshot but here it is again:

![image](https://user-images.githubusercontent.com/108122423/186100106-27254b4c-dcba-4d08-a909-09698398f99f.png)

BTW Culture is not a field in the UFRecords table but the screenshot shows a select *

Cheers
James

**Comment by AndyButland** [comment]
Ah, OK, I thought it was off the end of the screenshot.  That's unexpected then as you should have that field.

Would you mind please confirming you are definitely running 10.1, and share the results of this query?

```



Thanks again.

**Comment by jamesrichardbrett** [comment]
Hi Andy
Here are the relevant screenshots:

![image](https://user-images.githubusercontent.com/108122423/186107520-11c906e1-55df-4508-8130-52f3a477a2ac.png)

![image](https://user-images.githubusercontent.com/108122423/186107616-4daee651-7659-400b-a881-a98b9c7a9842.png)

![image](https://user-images.githubusercontent.com/108122423/186107735-2a406ee3-b68e-41d0-8d0c-1fe91e78e2f4.png)

Cheers
James

**Comment by AndyButland** [comment]
Thanks, That looks correct, and now I can see the `Culture` field, so when you shared the screenshots earlier and noted that field wasn't there, I guess it must have been on on a different or non-upgraded database.

So would you mind checking the original issue again, particularly for the record that you've shared in your latest update (i.e. the one with Id `63`)?

I believe you are running into the issue described under "Backoffice Date Formats" [here](https://umbraco.com/blog/umbraco-forms-release-candidates-81395101/), but that should be resolved by tracking the "Culture" for each submitted record and using that when rendering the dates in the back-office.

**Comment by jamesrichardbrett** [comment]
Hi Andy

When you say "but that should be resolved by us now", Does that mean in later version?

Cheers
James

**Comment by AndyButland** [comment]
Sorry for not being clear.  I meant that this issue should have been resolved in the version you are running.  I think the first screenshot you shared must have been from your database before you upgraded, and hence now you have, hopefully the issue you first reported will be resolved.  Of course, let me know though...

**Comment by jamesrichardbrett** [comment]
Hi Andy

Unfortunately I'm still seeing null in the data view:

![image](https://user-images.githubusercontent.com/108122423/186354711-2a53cca1-6bd8-4c76-a254-51f96b6c9e0f.png)

Incidentally if I edit the value

![image](https://user-images.githubusercontent.com/108122423/186354826-27d124c2-dffa-47ef-81c1-9a719f3aacef.png)

it then displays as expected

![image](https://user-images.githubusercontent.com/108122423/186355332-aef97dcb-bece-4ef1-b756-4717bfb88cbd.png)

In the list the edited dates appear in a different format to the those just enterer in the form:

![image](https://user-images.githubusercontent.com/108122423/186355498-86f7f95e-9596-4d45-985f-ebcde07b0feb.png)

Could this be a data format issue?

Cheers
James

**Comment by AndyButland** [comment]
Thanks for persevering with me... I've been able to replicate the problem now and have found the cause.  We'll have this fixed with the next patch releases.
