### ISSUE TITLE
Recaptch Score threshold no saved

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#967]
My Scrore thresold is 0.0 and I want to change it to 0.3. Problem is that it is not persisted after saving. It stays at 0.0.

Umbraco 11.1.0
Forms 11.0.1

**Comment by Trobeloo** [comment]
If I delete then recreate the question the score will be saved at 0.5 but if I try to change it, the new value won't be saved.

**Comment by AndyButland** [comment]
I think this duplicates [issue 955](https://github.com/umbraco/Umbraco.Forms.Issues/issues/955) which we've fixed in a release due out on Tuesday.

**Comment by Trobeloo** [comment]
I upgraded to Umbraco Forms: 11.0.2 but the problem remains. The score is 0 and if I change it to 0.5 it is not saved.

**Comment by AndyButland** [comment]
Could you please just ensure you have fully [cleared the cache](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html) in your back-office?  Thanks.

If so, and you still have the problem, I'll go back and have another look.

**Comment by Trobeloo** [comment]
I added the following to appsettings then restarted the Azure webApp but the problem is still there.
  "RuntimeMinification": {
        "UseInMemoryCache": true,
        "CacheBuster": "Version",
        "Version": "1"
      },

**Comment by AndyButland** [comment]
I'm afraid I'm still having trouble replicating the problem.  Would it be possible for you to export your form (right-click and choose _Export...) and either attach it here or if you prefer emailing it to me (abl AT umbraco DOT dk) please?  Maybe if I import it I'll see the same problem and can debug from there.

**Comment by AndyButland** [comment]
Thanks for sending the form over @Trobeloo.  I have managed to replicate now but it does look to still be caching related.  I've installed 11.0.1 and see the problem that I'd expected to see fixed in 11.0.2.  Then having installed 11.0.2 I could still see the same issue.

Having cleared the cache using the `RuntimeMinification` I found I could only clear the problem fully by ensuring the browser cache was fully cleared too.  To do this I loaded Chrome's dev tools, ticked the setting to "Disable cache (while dev tools are open)", and then did a refresh.  After that I could change the value in the reCAPTCHA slider.

Could you try that to see if it works for you please?

**Comment by AndyButland** [comment]
Hmm... OK, let me replay what I've done, and maybe you can please try repeating that to see if you still see the issue (or maybe can see what I'm missing in the steps where I'm trying to replicate).

- First of all I modified the form you exported and sent to me to remove the workflow (it is a custom one, so not one that exists in a new installation).  The workflows section now looks like this:

```
  "formWorkflows": {
    "onSubmit": [],
    "onApprove": []
  },
```

- I ran the following from a command line:

```
dotnet new install Umbraco.Templates
dotnet new umbraco --name RecaptchaTest
cd .\RecaptchaTest\
dotnet add package Umbraco.Forms
dotnet run
```
- Opened up the running Umbraco application and completed the installer
- Went to the forms section and imported the form you sent me (with the custom workflow removed).
- Edited the imported form, and changed the reCAPTCHA field's score threshold from 0.0 to 0.3, submitted and saved.
- Refreshed and edited the form again and can see the threshold is now 0.3.

**Comment by Trobeloo** [comment]
Created a new form using the "Contact form" template then added a reCaptcha 3 question that have a 5 threshold by default. It is still not possible to persits a new value (4).
